---
abstract: 'Client implementation of the Parallels Virtual Automation Agent API'
author:
  - 'Richard Simões <rsimoes AT cpan DOT org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
  Test::Requires: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300007, CPAN::Meta::Converter version 2.120351'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Parallels-Agent
no_index:
  namespace:
    - WWW::Parallels::Agent::Response
requires:
  File::ShareDir: 0
  Hash::FieldHash: 0
  IO::Socket: 0
  XML::Compile::Cache: 0
  namespace::clean: 0
  perl: v5.10
resources:
  bugtracker: https://github.com/rsimoes/www-parallels-agent/issues
  homepage: https://metacpan.org/release/WWW-Parallels-Agent
  repository: git://github.com/rsimoes/www-parallels-agent.git
version: v0.0.2
